name: movie-api
version: '3'

services:
  medexware-tools-api:
    image: movie-api
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:homero@localhost:5432/movies?schema=public
